// The map every flow on this page is drawn on. Boxes, zones and pods are fixed;
// a scenario is only an ordered list of hops across them, so the reader learns
// the territory once and afterwards watches a pen move over something familiar.

export interface Rect {
  x: number
  y: number
  w: number
  h: number
}

export interface Zone extends Rect {
  label: string
}

export interface Box extends Rect {
  label: string
  sub?: string
  kind: "declared" | "built" | "external"
}

export interface Step {
  from: string
  to: string
  label: string
  kind: "declared" | "built" | "token" | "gate"
  dashed?: boolean
  text: string
  who: string
  tokenName: string
  claims: [string, string][]
}

export interface Scenario {
  key: string
  name: string
  yaml: [string, "d" | "c"][]
  steps: Step[]
}

const SPIFFE = "spiffe://homelab.local/ns/orders/sa/orders-api"

export const ZONES: Record<string, Zone> = {
  cluster: { x: 216, y: 20, w: 596, h: 540, label: "the cluster" },
  node: { x: 416, y: 112, w: 352, h: 286, label: "node · work-2" },
  clouds: { x: 856, y: 20, w: 368, h: 320, label: "the clouds" },
}

export const PODS: Record<string, Zone> = {
  podA: { x: 428, y: 196, w: 178, h: 192, label: "orders-api pod" },
  podB: { x: 648, y: 196, w: 112, h: 192, label: "billing-api pod" },
}

export const BOXES: Record<string, Box> = {
  commit: {
    x: 16,
    y: 52,
    w: 146,
    h: 46,
    label: "The commit",
    sub: "one file, one team",
    kind: "declared",
  },
  browser: {
    x: 16,
    y: 132,
    w: 146,
    h: 46,
    label: "Browser",
    sub: "holds no token",
    kind: "external",
  },
  argocd: {
    x: 232,
    y: 50,
    w: 158,
    h: 44,
    label: "ArgoCD",
    sub: "applies what git says",
    kind: "built",
  },
  xp: { x: 470, y: 50, w: 168, h: 44, label: "Crossplane", sub: "builds the rest", kind: "built" },
  spireS: {
    x: 232,
    y: 124,
    w: 152,
    h: 44,
    label: "SPIRE server",
    sub: "the only signing key",
    kind: "built",
  },
  spireA: {
    x: 452,
    y: 142,
    w: 150,
    h: 42,
    label: "SPIRE agent",
    sub: "asks kubelet",
    kind: "built",
  },
  sidecar: {
    x: 440,
    y: 222,
    w: 154,
    h: 40,
    label: "credential sidecar",
    sub: "keeps files fresh",
    kind: "built",
  },
  app: {
    x: 440,
    y: 280,
    w: 154,
    h: 40,
    label: "orders-api",
    sub: "no credential in it",
    kind: "declared",
  },
  envoyO: { x: 440, y: 338, w: 154, h: 40, label: "Envoy", sub: "gates 1-2", kind: "built" },
  callee: { x: 658, y: 222, w: 92, h: 40, label: "billing-api", sub: "roles", kind: "declared" },
  envoyI: { x: 658, y: 338, w: 92, h: 40, label: "Envoy", sub: "gate 3", kind: "built" },
  oidc: {
    x: 232,
    y: 418,
    w: 254,
    h: 44,
    label: "OIDC JWKS",
    sub: "public, keys only",
    kind: "built",
  },
  istio: {
    x: 232,
    y: 482,
    w: 254,
    h: 44,
    label: "Istio policy",
    sub: "Sidecar + PeerAuthentication",
    kind: "built",
  },
  spaWeb: { x: 496, y: 418, w: 124, h: 44, label: "orders-web", sub: "nginx", kind: "declared" },
  podRep: { x: 640, y: 418, w: 128, h: 44, label: "reports-api", sub: "scp", kind: "declared" },
  binding: {
    x: 496,
    y: 482,
    w: 272,
    h: 44,
    label: "binding Secrets",
    sub: "ARNs, no credentials",
    kind: "built",
  },
  entra: {
    x: 872,
    y: 50,
    w: 336,
    h: 46,
    label: "Microsoft Entra",
    sub: "registration, federated credential",
    kind: "external",
  },
  sts: {
    x: 872,
    y: 124,
    w: 336,
    h: 42,
    label: "AWS STS",
    sub: "AssumeRoleWithWebIdentity",
    kind: "external",
  },
  iam: {
    x: 872,
    y: 190,
    w: 336,
    h: 42,
    label: "IAM role",
    sub: "trust = one SPIFFE ID",
    kind: "built",
  },
  s3: { x: 872, y: 256, w: 336, h: 46, label: "S3 bucket", sub: "and nothing else", kind: "built" },
}

export const SCENARIOS: Scenario[] = [
  {
    key: "provision",
    name: "One commit, day zero",
    yaml: [
      ["kind: Api", "c"],
      ["metadata:", "c"],
      ["  name: orders-api", "c"],
      ["spec:", "c"],
      ["  parameters:", "c"],
      ["    objectStorageRefs:", "d"],
      ["      - name: order-docs", "d"],
      ["    consumes:", "d"],
      ["      - app: billing-api", "d"],
      ["    provides:", "d"],
      ["      - name: ledger", "d"],
      ["        auth: workload", "d"],
      ["        allowedCallers:", "d"],
      ["          - app: orders-api", "d"],
    ],
    steps: [
      {
        from: "commit",
        to: "argocd",
        label: "one file",
        kind: "declared",
        text: "A team commits an Api resource naming what it needs, what it calls, and who holds its interfaces. That file is the only thing anyone writes by hand.",
        who: "Written by the <b>app team</b>. No ticket, no queue, no console.",
        tokenName: "What was asked for",
        claims: [
          ["a bucket", "objectStorageRefs"],
          ["a callee", "consumes"],
          ["an interface", "provides + allowedCallers"],
        ],
      },
      {
        from: "argocd",
        to: "xp",
        label: "applies the XR",
        kind: "built",
        text: "ArgoCD syncs it into the cluster and keeps it there. Delete anything downstream by hand and it comes back.",
        who: "Reconciled by <b>ArgoCD</b> and Crossplane. Drift is not a state this can rest in.",
        tokenName: "Now in the cluster",
        claims: [
          ["kind", "Api.platform.local.lab"],
          ["prune", "true"],
          ["selfHeal", "true"],
        ],
      },
      {
        from: "xp",
        to: "iam",
        label: "role + policy",
        kind: "built",
        text: "An IAM role appears whose trust policy names one exact SPIFFE ID, with a policy scoped to this bucket alone. Its ARN is predicted from the naming convention rather than read back, so role and pod are written in one pass.",
        who: "Built by <b>Crossplane</b>. This and the next three run in parallel.",
        tokenName: "Created in AWS",
        claims: [
          ["trust sub", `<em>${SPIFFE}</em>`],
          ["trust aud", "sts.amazonaws.com"],
          ["policy", "this bucket only"],
          ["ARN", "derived, not read back"],
        ],
      },
      {
        from: "xp",
        to: "entra",
        label: "registration",
        kind: "built",
        text: "An app registration, its service principal, a federated credential pinned to the same SPIFFE ID, and one app role per interface. Role GUIDs are hashed rather than fresh uuids, which would thrash the role.",
        who: "Built by <b>Crossplane</b>, in parallel with the AWS chain.",
        tokenName: "Created in Entra",
        claims: [
          ["issuer", "https://oidc.mattjarrett.dev"],
          ["sub", "the SPIFFE ID"],
          ["aud", "api://AzureADTokenExchange"],
          ["token version", "2, or the issuer is wrong"],
        ],
      },
      {
        from: "xp",
        to: "istio",
        label: "egress + mTLS",
        kind: "built",
        text: "The consumes list becomes this workload's egress allowance. Every workload also gets STRICT mTLS, so only pods in the mesh can reach it.",
        who: "Built by <b>Crossplane</b>. The app never sees an Istio kind or a SPIFFE string.",
        tokenName: "Created in the cluster",
        claims: [
          ["from consumes", "Sidecar egress, REGISTRY_ONLY"],
          ["on every workload", "PeerAuthentication, STRICT"],
          ["default", "nothing is reachable"],
        ],
      },
      {
        from: "xp",
        to: "binding",
        label: "one per ref",
        kind: "built",
        text: "One Secret per declared ref, carrying the role ARN and the metadata the app needs to find the thing. No credentials at all, so it is useless without a valid SVID behind it.",
        who: "Built by <b>Crossplane</b>. Three refs means three of these.",
        tokenName: "In the binding Secret",
        claims: [
          ["type", "s3"],
          ["role-arn", "arn:aws:iam::…:role/crossplane/…"],
          ["bucket", "platform-orders-order-docs"],
          ["credentials", "<em>none</em>"],
        ],
      },
      {
        from: "xp",
        to: "app",
        label: "Deployment",
        kind: "built",
        text: "The pod is rendered with the app container, the credential sidecar beside it, and an init container that blocks until the bindings land.",
        who: "Built by <b>Crossplane</b>. The team named an image; the shape of the pod is not theirs to choose.",
        tokenName: "Rendered into the pod",
        claims: [
          ["containers", "app + credential sidecar"],
          ["init", "waits on /bindings"],
          ["volumes", "SPIFFE CSI socket, bindings"],
        ],
      },
      {
        from: "binding",
        to: "sidecar",
        label: "mounted at /bindings",
        kind: "built",
        text: "The init container polls for the last key written to that volume. Expect Init:0/4 for 60 to 90 seconds on a first provision. That reads as working; a Pending pod would read as broken.",
        who: "Ordering enforced by <b>Kubernetes</b>. Images pull only after every init container clears.",
        tokenName: "What it waits for",
        claims: [
          ["path", "/bindings/order-docs/type"],
          ["status", "<em>Init:0/4</em>, 60-90s"],
          ["then", "images pull"],
        ],
      },
      {
        from: "sidecar",
        to: "sidecar",
        label: "first exchange",
        kind: "built",
        text: "The sidecar starts, fetches its first SVID and runs the first exchange. Expect the Entra grant to sit red for about thirty seconds while the role replicates to its principal. It self heals.",
        who: "Started by the <b>kubelet</b>, credentialed by SPIRE. The one genuinely slow thing on this map.",
        tokenName: "First exchange",
        claims: [
          ["AWS", "credentials file written"],
          ["Entra", "token file written"],
          ["grant", "red ~30s, then green"],
        ],
      },
      {
        from: "app",
        to: "app",
        label: "2/2 Running",
        kind: "declared",
        text: "The app container starts last, into a pod where the files it needs already exist. No cloud SDK for fetching secrets, no platform-specific code. From here every call it makes is one of the other four tabs.",
        who: "Running as the <b>app team</b> wrote it. Hand-made objects on this whole map: one, the commit.",
        tokenName: "Ready",
        claims: [
          ["status", "2/2 Running"],
          ["waited on", "Crossplane, then both clouds"],
          ["secrets typed by a human", "none"],
        ],
      },
    ],
  },

  {
    key: "workload",
    name: "API calls API",
    yaml: [
      ["orders-api", "c"],
      ["consumes:", "d"],
      ["  - app: billing-api", "d"],
      ["", "c"],
      ["billing-api", "c"],
      ["provides:", "d"],
      ["  - name: ledger", "d"],
      ["    auth: workload", "d"],
      ["    allowedCallers:", "d"],
      ["      - app: orders-api", "d"],
    ],
    steps: [
      {
        from: "spireS",
        to: "spireA",
        label: "signs the SVID",
        kind: "built",
        text: "The server holds the only signing key. The agent runs on every node and holds none, so a compromised node cannot mint an identity for anything.",
        who: "Both built by <b>SPIRE</b>. The agent asks, the server signs.",
        tokenName: "Where identity starts",
        claims: [
          ["trust domain", "homelab.local"],
          ["signing key", "server only"],
          ["agent holds", "no key"],
        ],
      },
      {
        from: "spireA",
        to: "sidecar",
        label: "CSI socket",
        kind: "built",
        text: "The sidecar asks over a Unix socket the CSI driver mounted into the pod. The agent checks with the node's kubelet which pod is on the other end before anything is signed.",
        who: "Delivered by the <b>agent</b>. A stolen manifest is not an identity: the answer depends on what is running.",
        tokenName: "JWT-SVID",
        claims: [
          ["over", "Workload API, CSI-mounted socket"],
          ["sub", SPIFFE],
          ["aud", "<em>api://AzureADTokenExchange</em>"],
          ["exp", "in 5 minutes"],
        ],
      },
      {
        from: "sidecar",
        to: "sidecar",
        label: "writes the file",
        kind: "built",
        text: "The sidecar writes the raw token to a file both containers share, and repeats every 240s. For Entra that is its whole job: it never opens a connection to Microsoft at all.",
        who: "The <b>sidecar</b> talks to SPIRE and nobody else here. Entra is the app's business.",
        tokenName: "At rest",
        claims: [
          ["file", "/entra-identity/token"],
          ["written by", "the sidecar"],
          ["read by", "the app"],
          ["calls Entra", "<em>never</em>"],
        ],
      },
      {
        from: "app",
        to: "entra",
        label: "client_assertion",
        kind: "token",
        text: "The app's own Azure SDK reads that file and swaps it for a real access token - the same WorkloadIdentityCredential that AKS sets up natively.",
        who: "Sent by the <b>app</b>, using a file it did not fetch and env vars it did not write.",
        tokenName: "Presented to Entra",
        claims: [
          ["assertion", "the file on disk"],
          ["client_id", "AZURE_CLIENT_ID"],
          ["token file", "AZURE_FEDERATED_TOKEN_FILE"],
          ["scope", "api://billing-api/.default"],
        ],
      },
      {
        from: "entra",
        to: "oidc",
        label: "fetch public keys",
        kind: "built",
        dashed: true,
        text: "Entra fetches the cluster's public signing keys and checks the signature itself. Nothing was ever shared with it.",
        who: "Checked by <b>Entra</b> against a key it pulled, not a secret it was given.",
        tokenName: "Being verified",
        claims: [
          ["signature", "against published JWKS"],
          ["sub", "literal match, no wildcards"],
          ["aud", "literal match"],
        ],
      },
      {
        from: "entra",
        to: "app",
        label: "access token",
        kind: "token",
        text: "Back comes an access token carrying a roles claim, because billing-api's allowedCallers list names orders-api.",
        who: "Granted because <b>billing-api's own file</b> says so.",
        tokenName: "Entra access token",
        claims: [
          ["aud", "api://billing-api"],
          ["roles", '<em>["ledger"]</em>'],
          ["appid", "orders-api"],
          ["exp", "in 1 hour"],
        ],
      },
      {
        from: "envoyO",
        to: "envoyO",
        label: "gates 1 + 2",
        kind: "gate",
        text: "Leaving the pod, its own Envoy checks the destination is in this workload's egress list and registered in the mesh. Registered is not permitted.",
        who: "Enforced by <b>Istio</b>, rendered from consumes. Refused here looks like a 502 that never left the pod.",
        tokenName: "Mesh check",
        claims: [
          ["gate 1", "Sidecar egress, REGISTRY_ONLY"],
          ["gate 2", "host in the registry"],
          ["fails as", "blackholed at source"],
        ],
      },
      {
        from: "envoyO",
        to: "envoyI",
        label: "mTLS",
        kind: "gate",
        text: "Arriving, the callee's Envoy demands a real mTLS identity from the cluster CA. It does not choose callers, and never opens the token.",
        who: "Enforced by <b>Istio</b>. It issues its own X.509 SVID for this, separate from the JWT one.",
        tokenName: "Peer identity",
        claims: [
          ["principal", SPIFFE],
          ["gate 3", "PeerAuthentication, mTLS"],
          ["fails as", "connection reset"],
        ],
      },
      {
        from: "envoyI",
        to: "callee",
        label: "roles check",
        kind: "declared",
        text: "Gate 4 is app code. Only billing-api knows which of its own routes needs the ledger role, so only billing-api reads the claim.",
        who: "Decided by the <b>app</b>. One boundary, not two.",
        tokenName: "What the app sees",
        claims: [
          ["roles", '<em>["ledger"]</em>'],
          ["route", "GET /ledger"],
          ["result", "200"],
        ],
      },
    ],
  },

  {
    key: "pkce",
    name: "SPA sign-in (PKCE)",
    yaml: [
      ["orders-web", "c"],
      ["userAuth:", "d"],
      ["  client: orders-api", "d"],
      ["  scopes: [profile]", "d"],
      ["apiProxies:", "d"],
      ["  - app: orders-api", "d"],
      ["    path: /api", "d"],
      ["host: orders.example.dev", "d"],
    ],
    steps: [
      {
        from: "browser",
        to: "entra",
        label: "code_challenge S256",
        kind: "token",
        text: "Sign-in starts with a redirect carrying the SHA-256 of a random secret the client just invented. The secret itself stays put.",
        who: "Required because a <b>browser cannot keep a secret</b>. Everything it ships is readable.",
        tokenName: "Authorize request",
        claims: [
          ["client_id", "public, by design"],
          ["code_challenge", "<em>SHA-256(verifier)</em>"],
          ["method", "S256"],
          ["redirect_uri", "derived from host"],
        ],
      },
      {
        from: "entra",
        to: "browser",
        label: "authorization code",
        kind: "token",
        text: "The person signs in and a code comes back through the address bar. Anyone who sees that URL holds the code, and the code alone is now useless.",
        who: "Redirect URIs are an <b>allow-list</b>, derived from the app's host. Nobody types one.",
        tokenName: "In the URL",
        claims: [
          ["code", "single use"],
          ["stolen?", "worthless without the verifier"],
        ],
      },
      {
        from: "browser",
        to: "spaWeb",
        label: "POST /api/auth",
        kind: "declared",
        text: "The code goes to the app's own backend, through the SPA's proxy. Page scripts are couriers here and nothing more.",
        who: "Routed by the <b>Spa composition</b>, which rewrites Host so Envoy can find the upstream.",
        tokenName: "On the wire",
        claims: [
          ["code", "in the request body"],
          ["Host", "orders-api.orders.svc"],
          ["X-Forwarded-Host", "orders.example.dev"],
        ],
      },
      {
        from: "spaWeb",
        to: "envoyO",
        label: "gates 1-3",
        kind: "gate",
        text: "Same three mesh gates as any other call. A sign-in is not special-cased.",
        who: "Enforced by <b>Istio</b> from the apiProxies entry. No extra declaration.",
        tokenName: "Mesh check",
        claims: [
          ["gates", "egress, registry, mTLS"],
          ["fails as", "502 or connection reset"],
        ],
      },
      {
        from: "envoyO",
        to: "app",
        label: "",
        kind: "declared",
        text: "The backend proves it started this flow by producing the raw verifier that hashes to the challenge sent in step one. No workload identity is involved.",
        who: "This is the whole of <b>PKCE</b>. It proves same-party, not which app.",
        tokenName: "Held by the backend",
        claims: [
          ["code_verifier", "43-128 random chars"],
          ["left the app", "<em>never</em>"],
        ],
      },
      {
        from: "app",
        to: "entra",
        label: "code + verifier",
        kind: "token",
        text: "Entra hashes what it received and compares it to what it stored. A mismatch means no token, whoever is asking.",
        who: "Checked by <b>Entra</b>. Reversing SHA-256 is the attacker's problem.",
        tokenName: "Token request",
        claims: [
          ["code", "from step 2"],
          ["code_verifier", "<em>raw secret</em>"],
          ["grant_type", "authorization_code"],
        ],
      },
      {
        from: "entra",
        to: "app",
        label: "id + access + refresh",
        kind: "token",
        text: "Three tokens arrive and all three stop here. This is the reason the flow is worth the extra hop.",
        who: "Kept by the <b>backend</b> named in userAuth.client. Only one backend owns the session.",
        tokenName: "Entra tokens",
        claims: [
          ["aud", "api://orders-api"],
          ["scp", "profile"],
          ["sub", "the signed-in person"],
          ["stored", "server side only"],
        ],
      },
      {
        from: "app",
        to: "browser",
        label: "httpOnly session cookie",
        kind: "built",
        text: "The browser gets a cookie script cannot read. No access token reaches page JavaScript, so XSS cannot steal one.",
        who: "Set by the <b>backend</b>. The implicit flow put the token in the URL, which is why it is gone.",
        tokenName: "What the browser holds",
        claims: [
          ["cookie", "httpOnly, Secure, SameSite"],
          ["access token", "<em>none</em>"],
          ["readable by JS", "no"],
        ],
      },
    ],
  },

  {
    key: "obo",
    name: "Calling as the user (OBO)",
    yaml: [
      ["orders-api", "c"],
      ["consumes:", "d"],
      ["  - app: reports-api", "d"],
      ["", "c"],
      ["reports-api", "c"],
      ["provides:", "d"],
      ["  - name: exports", "d"],
      ["    auth: user", "d"],
      ["    allowedCallers:", "d"],
      ["      - app: orders-api", "d"],
    ],
    steps: [
      {
        from: "browser",
        to: "app",
        label: "session cookie",
        kind: "declared",
        text: "A person clicks export. The backend looks up its session and finds the access token it kept at sign-in.",
        who: "The token's <b>aud is this backend</b>, which matters in three steps.",
        tokenName: "User token, at rest",
        claims: [
          ["aud", "<em>api://orders-api</em>"],
          ["sub", "the signed-in person"],
          ["scp", "profile"],
        ],
      },
      {
        from: "spireS",
        to: "spireA",
        label: "signs the SVID",
        kind: "built",
        text: "To act for that person elsewhere, the backend must first prove it is itself. That proof starts where every identity here starts.",
        who: "Built by <b>SPIRE</b>. There is no client secret anywhere in this pod.",
        tokenName: "Where identity starts",
        claims: [
          ["trust domain", "homelab.local"],
          ["signing key", "server only"],
          ["agent holds", "no key"],
        ],
      },
      {
        from: "spireA",
        to: "sidecar",
        label: "CSI socket",
        kind: "built",
        text: "Same delivery as any workload: the agent checks with kubelet who is asking, and a fresh SVID lands in a file the app reads.",
        who: "Delivered by the <b>agent</b>. The sidecar never contacts Entra here either.",
        tokenName: "JWT-SVID",
        claims: [
          ["over", "Workload API, CSI-mounted socket"],
          ["sub", SPIFFE],
          ["aud", "api://AzureADTokenExchange"],
          ["used as", "client_assertion"],
        ],
      },
      {
        from: "app",
        to: "entra",
        label: "OBO exchange",
        kind: "token",
        text: "Three things go up together: who I am, who I am acting for, and where I want to go.",
        who: "Sent by the <b>app</b>. Entra refuses a user token issued for anyone else.",
        tokenName: "OBO request",
        claims: [
          ["grant_type", "jwt-bearer"],
          ["client_assertion", "the SVID file"],
          ["assertion", "the user token"],
          ["scope", "api://reports-api/.default"],
        ],
      },
      {
        from: "entra",
        to: "app",
        label: "delegated token",
        kind: "token",
        text: "What comes back still carries the person, because reports-api declared the interface as auth: user - a delegated scope, not an app role.",
        who: "Granted because <b>reports-api's allowedCallers</b> names this backend.",
        tokenName: "Delegated access token",
        claims: [
          ["aud", "api://reports-api"],
          ["sub", "<em>still the person</em>"],
          ["scp", "<em>exports</em>"],
          ["roles", "absent"],
        ],
      },
      {
        from: "envoyO",
        to: "envoyO",
        label: "gates 1-3",
        kind: "gate",
        text: "The mesh does not care whose token this is. It checks the call was declared and the caller holds a mesh certificate, and would refuse an app holding a perfect token.",
        who: "Enforced by <b>Istio</b>. Identity of the caller, not identity of the user.",
        tokenName: "Mesh check",
        claims: [
          ["principal", "spiffe://.../sa/orders-api"],
          ["gate 3", "PeerAuthentication, mTLS"],
          ["reads the token", "<em>no</em>"],
        ],
      },
      {
        from: "envoyO",
        to: "podRep",
        label: "scp check",
        kind: "declared",
        text: "The downstream app sees a scope, not a role, and knows a person is behind the call. That difference is the whole point of the flow.",
        who: "Decided by <b>reports-api</b>. scp means acting for someone, roles means acting as itself.",
        tokenName: "What the app sees",
        claims: [
          ["scp", "<em>exports</em>  (a string)"],
          ["roles", "absent (an array)"],
          ["sub", "the person, for the audit log"],
        ],
      },
    ],
  },

  {
    key: "aws",
    name: "Reaching AWS",
    yaml: [
      ["orders-api", "c"],
      ["objectStorageRefs:", "d"],
      ["  - name: order-docs", "d"],
      ["nosqlRef:", "d"],
      ["  name: order-index", "d"],
    ],
    steps: [
      {
        from: "xp",
        to: "iam",
        label: "at commit time",
        kind: "built",
        text: "Long before this call, the commit produced a role whose trust policy names one exact SPIFFE ID, with a policy scoped to one bucket.",
        who: "Built by <b>Crossplane</b>. Everything after this is runtime.",
        tokenName: "The trust policy",
        claims: [
          ["Federated", "https://oidc.mattjarrett.dev"],
          ["sub", `<em>${SPIFFE}</em>`],
          ["aud", "sts.amazonaws.com"],
          ["policy", "this bucket only"],
        ],
      },
      {
        from: "spireS",
        to: "spireA",
        label: "signs the SVID",
        kind: "built",
        text: "At runtime, identity starts in the same place it always does. The server holds the signing key; the agent on this node holds none.",
        who: "Both built by <b>SPIRE</b>. Nothing about AWS is special here.",
        tokenName: "Where identity starts",
        claims: [
          ["trust domain", "homelab.local"],
          ["signing key", "server only"],
          ["agent holds", "no key"],
        ],
      },
      {
        from: "spireA",
        to: "sidecar",
        label: "CSI socket",
        kind: "built",
        text: "The agent confirms with kubelet which pod is asking, then answers with a JWT-SVID whose audience is sts.amazonaws.com. The app container is not on this path.",
        who: "Delivered by the <b>agent</b>, to the sidecar only.",
        tokenName: "JWT-SVID",
        claims: [
          ["over", "Workload API, CSI-mounted socket"],
          ["sub", SPIFFE],
          ["aud", "<em>sts.amazonaws.com</em>"],
          ["exp", "in 5 minutes"],
        ],
      },
      {
        from: "sidecar",
        to: "sts",
        label: "AssumeRoleWithWebIdentity",
        kind: "token",
        text: "Here the sidecar calls the cloud itself, the opposite of the Entra case. It presents the same token once per binding, naming a different role each time. One role per pod is an AWS SDK limit, not a protocol one.",
        who: "Sent by the <b>sidecar</b>. This is why the platform owns one instead of using stock IRSA.",
        tokenName: "Presented to STS",
        claims: [
          ["token", "the JWT-SVID"],
          ["RoleArn", "arn:aws:iam::…:role/crossplane/…"],
          ["calls", "one per declared ref"],
        ],
      },
      {
        from: "sts",
        to: "oidc",
        label: "fetch public keys",
        kind: "built",
        dashed: true,
        text: "STS verifies the signature against keys it fetches from the cluster, then matches sub and aud as literal strings. Rename the service account and access is lost.",
        who: "Checked by <b>AWS</b>. No secret was ever exchanged with it.",
        tokenName: "Being verified",
        claims: [
          ["signature", "against published JWKS"],
          ["sub", "exact match"],
          ["aud", "exact match"],
        ],
      },
      {
        from: "sts",
        to: "sidecar",
        label: "1h credentials",
        kind: "token",
        text: "Credentials come back to the sidecar, which repeats the exchange at fifty minutes. A failed one leaves the old file alone rather than crashing, since it is good for up to an hour.",
        who: "Received by the <b>sidecar</b>. The app has no idea this happened.",
        tokenName: "Short-lived credentials",
        claims: [
          ["access key", "expires in 1 hour"],
          ["refreshed at", "50 minutes"],
          ["on failure", "keep the old file, retry in 30s"],
        ],
      },
      {
        from: "sidecar",
        to: "sidecar",
        label: "writes profiles",
        kind: "built",
        text: "It writes one named profile per binding into a file both containers share. Nothing longer-lived than an hour is ever on that disk.",
        who: "The <b>split</b> is the point: credentials live in the sidecar's half, the app only reads a profile name.",
        tokenName: "At rest",
        claims: [
          ["file", "/aws-credentials/credentials"],
          ["profiles", "one per declared ref"],
          ["written by", "the sidecar"],
        ],
      },
      {
        from: "app",
        to: "s3",
        label: "signed request",
        kind: "declared",
        text: "The app loads the profile whose env var name the platform derived, and calls S3 with a stock SDK. Its DynamoDB role cannot touch this bucket.",
        who: "One role per binding, so a compromised pod's blast radius is <b>one resource</b>.",
        tokenName: "App code",
        claims: [
          ["env", "AWS_PROFILE_OBJECT_STORAGE_ORDER_DOCS"],
          ["reach", "this bucket"],
          ["cannot reach", "<em>the table, the database</em>"],
        ],
      },
    ],
  },
]
